// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_index.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockIndex struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ParentBlockId        []byte   `protobuf:"bytes,2,opt,name=parent_block_id,json=parentBlockId,proto3" json:"parent_block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockIndex) Reset()         { *m = BlockIndex{} }
func (m *BlockIndex) String() string { return proto.CompactTextString(m) }
func (*BlockIndex) ProtoMessage()    {}
func (*BlockIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4a72c8d1b448497, []int{0}
}

func (m *BlockIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockIndex.Unmarshal(m, b)
}
func (m *BlockIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockIndex.Marshal(b, m, deterministic)
}
func (m *BlockIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockIndex.Merge(m, src)
}
func (m *BlockIndex) XXX_Size() int {
	return xxx_messageInfo_BlockIndex.Size(m)
}
func (m *BlockIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockIndex.DiscardUnknown(m)
}

var xxx_messageInfo_BlockIndex proto.InternalMessageInfo

func (m *BlockIndex) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *BlockIndex) GetParentBlockId() []byte {
	if m != nil {
		return m.ParentBlockId
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockIndex)(nil), "types.BlockIndex")
}

func init() { proto.RegisterFile("block_index.proto", fileDescriptor_b4a72c8d1b448497) }

var fileDescriptor_b4a72c8d1b448497 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xca, 0xc9, 0x4f,
	0xce, 0x8e, 0xcf, 0xcc, 0x4b, 0x49, 0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d,
	0xa9, 0x2c, 0x48, 0x2d, 0x56, 0xf2, 0xe7, 0xe2, 0x72, 0x02, 0xc9, 0x79, 0x82, 0xa4, 0x84, 0x24,
	0xb9, 0x38, 0xa0, 0x2a, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xd8, 0xc1, 0x7c, 0xcf,
	0x14, 0x21, 0x35, 0x2e, 0xfe, 0x82, 0xc4, 0xa2, 0xd4, 0xbc, 0x92, 0x78, 0xb8, 0x0a, 0x26, 0xb0,
	0x0a, 0x5e, 0x88, 0x30, 0xc4, 0x94, 0x94, 0x24, 0x36, 0xb0, 0xf1, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x37, 0xcb, 0x29, 0x73, 0x00, 0x00, 0x00,
}
