// Code generated by protoc-gen-go. DO NOT EDIT.
// source: explorer.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockRequestItem struct {
	// Types that are valid to be assigned to BlockRequestedItems:
	//	*BlockRequestItem_BlockIdItem
	//	*BlockRequestItem_GetBlockSummaryListRequestItem
	//	*BlockRequestItem_LatestBlockHeightRequestItem
	//	*BlockRequestItem_DifficultHashRateRequestItem
	BlockRequestedItems  isBlockRequestItem_BlockRequestedItems `protobuf_oneof:"block_requested_items"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *BlockRequestItem) Reset()         { *m = BlockRequestItem{} }
func (m *BlockRequestItem) String() string { return proto.CompactTextString(m) }
func (*BlockRequestItem) ProtoMessage()    {}
func (*BlockRequestItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{0}
}

func (m *BlockRequestItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequestItem.Unmarshal(m, b)
}
func (m *BlockRequestItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequestItem.Marshal(b, m, deterministic)
}
func (m *BlockRequestItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequestItem.Merge(m, src)
}
func (m *BlockRequestItem) XXX_Size() int {
	return xxx_messageInfo_BlockRequestItem.Size(m)
}
func (m *BlockRequestItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequestItem.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequestItem proto.InternalMessageInfo

type isBlockRequestItem_BlockRequestedItems interface {
	isBlockRequestItem_BlockRequestedItems()
}

type BlockRequestItem_BlockIdItem struct {
	BlockIdItem *BlockId `protobuf:"bytes,1,opt,name=block_id_item,json=blockIdItem,proto3,oneof"`
}

type BlockRequestItem_GetBlockSummaryListRequestItem struct {
	GetBlockSummaryListRequestItem *GetBlockSummaryListRequest `protobuf:"bytes,2,opt,name=get_block_summary_list_request_item,json=getBlockSummaryListRequestItem,proto3,oneof"`
}

type BlockRequestItem_LatestBlockHeightRequestItem struct {
	LatestBlockHeightRequestItem *empty.Empty `protobuf:"bytes,3,opt,name=latest_block_height_request_item,json=latestBlockHeightRequestItem,proto3,oneof"`
}

type BlockRequestItem_DifficultHashRateRequestItem struct {
	DifficultHashRateRequestItem *empty.Empty `protobuf:"bytes,4,opt,name=difficult_hash_rate_request_item,json=difficultHashRateRequestItem,proto3,oneof"`
}

func (*BlockRequestItem_BlockIdItem) isBlockRequestItem_BlockRequestedItems() {}

func (*BlockRequestItem_GetBlockSummaryListRequestItem) isBlockRequestItem_BlockRequestedItems() {}

func (*BlockRequestItem_LatestBlockHeightRequestItem) isBlockRequestItem_BlockRequestedItems() {}

func (*BlockRequestItem_DifficultHashRateRequestItem) isBlockRequestItem_BlockRequestedItems() {}

func (m *BlockRequestItem) GetBlockRequestedItems() isBlockRequestItem_BlockRequestedItems {
	if m != nil {
		return m.BlockRequestedItems
	}
	return nil
}

func (m *BlockRequestItem) GetBlockIdItem() *BlockId {
	if x, ok := m.GetBlockRequestedItems().(*BlockRequestItem_BlockIdItem); ok {
		return x.BlockIdItem
	}
	return nil
}

func (m *BlockRequestItem) GetGetBlockSummaryListRequestItem() *GetBlockSummaryListRequest {
	if x, ok := m.GetBlockRequestedItems().(*BlockRequestItem_GetBlockSummaryListRequestItem); ok {
		return x.GetBlockSummaryListRequestItem
	}
	return nil
}

func (m *BlockRequestItem) GetLatestBlockHeightRequestItem() *empty.Empty {
	if x, ok := m.GetBlockRequestedItems().(*BlockRequestItem_LatestBlockHeightRequestItem); ok {
		return x.LatestBlockHeightRequestItem
	}
	return nil
}

func (m *BlockRequestItem) GetDifficultHashRateRequestItem() *empty.Empty {
	if x, ok := m.GetBlockRequestedItems().(*BlockRequestItem_DifficultHashRateRequestItem); ok {
		return x.DifficultHashRateRequestItem
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BlockRequestItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BlockRequestItem_BlockIdItem)(nil),
		(*BlockRequestItem_GetBlockSummaryListRequestItem)(nil),
		(*BlockRequestItem_LatestBlockHeightRequestItem)(nil),
		(*BlockRequestItem_DifficultHashRateRequestItem)(nil),
	}
}

type BlockResponseItem struct {
	// Types that are valid to be assigned to BlockResponseItems:
	//	*BlockResponseItem_GetBlockByBlockIdResponseItem
	//	*BlockResponseItem_GetBlockSummaryListResponseItem
	//	*BlockResponseItem_LatestBlockHeightResponseItem
	//	*BlockResponseItem_DifficultHashRateResponseItem
	BlockResponseItems   isBlockResponseItem_BlockResponseItems `protobuf_oneof:"block_response_items"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *BlockResponseItem) Reset()         { *m = BlockResponseItem{} }
func (m *BlockResponseItem) String() string { return proto.CompactTextString(m) }
func (*BlockResponseItem) ProtoMessage()    {}
func (*BlockResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{1}
}

func (m *BlockResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponseItem.Unmarshal(m, b)
}
func (m *BlockResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponseItem.Marshal(b, m, deterministic)
}
func (m *BlockResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponseItem.Merge(m, src)
}
func (m *BlockResponseItem) XXX_Size() int {
	return xxx_messageInfo_BlockResponseItem.Size(m)
}
func (m *BlockResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponseItem proto.InternalMessageInfo

type isBlockResponseItem_BlockResponseItems interface {
	isBlockResponseItem_BlockResponseItems()
}

type BlockResponseItem_GetBlockByBlockIdResponseItem struct {
	GetBlockByBlockIdResponseItem *GetBlockByBlockIdResponse `protobuf:"bytes,1,opt,name=get_block_by_block_id_response_item,json=getBlockByBlockIdResponseItem,proto3,oneof"`
}

type BlockResponseItem_GetBlockSummaryListResponseItem struct {
	GetBlockSummaryListResponseItem *GetBlockSummaryListResponse `protobuf:"bytes,2,opt,name=get_block_summary_list_response_item,json=getBlockSummaryListResponseItem,proto3,oneof"`
}

type BlockResponseItem_LatestBlockHeightResponseItem struct {
	LatestBlockHeightResponseItem *LatestBlockHeightResponse `protobuf:"bytes,3,opt,name=latest_block_height_response_item,json=latestBlockHeightResponseItem,proto3,oneof"`
}

type BlockResponseItem_DifficultHashRateResponseItem struct {
	DifficultHashRateResponseItem *DifficultHashRate `protobuf:"bytes,4,opt,name=difficult_hash_rate_response_item,json=difficultHashRateResponseItem,proto3,oneof"`
}

func (*BlockResponseItem_GetBlockByBlockIdResponseItem) isBlockResponseItem_BlockResponseItems() {}

func (*BlockResponseItem_GetBlockSummaryListResponseItem) isBlockResponseItem_BlockResponseItems() {}

func (*BlockResponseItem_LatestBlockHeightResponseItem) isBlockResponseItem_BlockResponseItems() {}

func (*BlockResponseItem_DifficultHashRateResponseItem) isBlockResponseItem_BlockResponseItems() {}

func (m *BlockResponseItem) GetBlockResponseItems() isBlockResponseItem_BlockResponseItems {
	if m != nil {
		return m.BlockResponseItems
	}
	return nil
}

func (m *BlockResponseItem) GetGetBlockByBlockIdResponseItem() *GetBlockByBlockIdResponse {
	if x, ok := m.GetBlockResponseItems().(*BlockResponseItem_GetBlockByBlockIdResponseItem); ok {
		return x.GetBlockByBlockIdResponseItem
	}
	return nil
}

func (m *BlockResponseItem) GetGetBlockSummaryListResponseItem() *GetBlockSummaryListResponse {
	if x, ok := m.GetBlockResponseItems().(*BlockResponseItem_GetBlockSummaryListResponseItem); ok {
		return x.GetBlockSummaryListResponseItem
	}
	return nil
}

func (m *BlockResponseItem) GetLatestBlockHeightResponseItem() *LatestBlockHeightResponse {
	if x, ok := m.GetBlockResponseItems().(*BlockResponseItem_LatestBlockHeightResponseItem); ok {
		return x.LatestBlockHeightResponseItem
	}
	return nil
}

func (m *BlockResponseItem) GetDifficultHashRateResponseItem() *DifficultHashRate {
	if x, ok := m.GetBlockResponseItems().(*BlockResponseItem_DifficultHashRateResponseItem); ok {
		return x.DifficultHashRateResponseItem
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BlockResponseItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BlockResponseItem_GetBlockByBlockIdResponseItem)(nil),
		(*BlockResponseItem_GetBlockSummaryListResponseItem)(nil),
		(*BlockResponseItem_LatestBlockHeightResponseItem)(nil),
		(*BlockResponseItem_DifficultHashRateResponseItem)(nil),
	}
}

////////////////////////////////////
type BlockSummary struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ParentId             []byte   `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	AccumulatorRootHash  []byte   `protobuf:"bytes,4,opt,name=accumulator_root_hash,json=accumulatorRootHash,proto3" json:"accumulator_root_hash,omitempty"`
	StateRootHash        []byte   `protobuf:"bytes,5,opt,name=state_root_hash,json=stateRootHash,proto3" json:"state_root_hash,omitempty"`
	Miner                []byte   `protobuf:"bytes,6,opt,name=miner,proto3" json:"miner,omitempty"`
	Nonce                uint64   `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Target               []byte   `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Algo                 uint32   `protobuf:"varint,9,opt,name=algo,proto3" json:"algo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSummary) Reset()         { *m = BlockSummary{} }
func (m *BlockSummary) String() string { return proto.CompactTextString(m) }
func (*BlockSummary) ProtoMessage()    {}
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{2}
}

func (m *BlockSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSummary.Unmarshal(m, b)
}
func (m *BlockSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSummary.Marshal(b, m, deterministic)
}
func (m *BlockSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSummary.Merge(m, src)
}
func (m *BlockSummary) XXX_Size() int {
	return xxx_messageInfo_BlockSummary.Size(m)
}
func (m *BlockSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSummary.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSummary proto.InternalMessageInfo

func (m *BlockSummary) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *BlockSummary) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockSummary) GetParentId() []byte {
	if m != nil {
		return m.ParentId
	}
	return nil
}

func (m *BlockSummary) GetAccumulatorRootHash() []byte {
	if m != nil {
		return m.AccumulatorRootHash
	}
	return nil
}

func (m *BlockSummary) GetStateRootHash() []byte {
	if m != nil {
		return m.StateRootHash
	}
	return nil
}

func (m *BlockSummary) GetMiner() []byte {
	if m != nil {
		return m.Miner
	}
	return nil
}

func (m *BlockSummary) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockSummary) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *BlockSummary) GetAlgo() uint32 {
	if m != nil {
		return m.Algo
	}
	return 0
}

type GetBlockSummaryListRequest struct {
	BlockId              *BlockId `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockSummaryListRequest) Reset()         { *m = GetBlockSummaryListRequest{} }
func (m *GetBlockSummaryListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockSummaryListRequest) ProtoMessage()    {}
func (*GetBlockSummaryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{3}
}

func (m *GetBlockSummaryListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockSummaryListRequest.Unmarshal(m, b)
}
func (m *GetBlockSummaryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockSummaryListRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockSummaryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockSummaryListRequest.Merge(m, src)
}
func (m *GetBlockSummaryListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockSummaryListRequest.Size(m)
}
func (m *GetBlockSummaryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockSummaryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockSummaryListRequest proto.InternalMessageInfo

func (m *GetBlockSummaryListRequest) GetBlockId() *BlockId {
	if m != nil {
		return m.BlockId
	}
	return nil
}

type BlockId struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockId) Reset()         { *m = BlockId{} }
func (m *BlockId) String() string { return proto.CompactTextString(m) }
func (*BlockId) ProtoMessage()    {}
func (*BlockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{4}
}

func (m *BlockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockId.Unmarshal(m, b)
}
func (m *BlockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockId.Marshal(b, m, deterministic)
}
func (m *BlockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockId.Merge(m, src)
}
func (m *BlockId) XXX_Size() int {
	return xxx_messageInfo_BlockId.Size(m)
}
func (m *BlockId) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockId.DiscardUnknown(m)
}

var xxx_messageInfo_BlockId proto.InternalMessageInfo

func (m *BlockId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockSummaryListResponse struct {
	Blocks               []*BlockSummary `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBlockSummaryListResponse) Reset()         { *m = GetBlockSummaryListResponse{} }
func (m *GetBlockSummaryListResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockSummaryListResponse) ProtoMessage()    {}
func (*GetBlockSummaryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{5}
}

func (m *GetBlockSummaryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockSummaryListResponse.Unmarshal(m, b)
}
func (m *GetBlockSummaryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockSummaryListResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockSummaryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockSummaryListResponse.Merge(m, src)
}
func (m *GetBlockSummaryListResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockSummaryListResponse.Size(m)
}
func (m *GetBlockSummaryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockSummaryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockSummaryListResponse proto.InternalMessageInfo

func (m *GetBlockSummaryListResponse) GetBlocks() []*BlockSummary {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type LatestBlockHeightResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestBlockHeightResponse) Reset()         { *m = LatestBlockHeightResponse{} }
func (m *LatestBlockHeightResponse) String() string { return proto.CompactTextString(m) }
func (*LatestBlockHeightResponse) ProtoMessage()    {}
func (*LatestBlockHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{6}
}

func (m *LatestBlockHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestBlockHeightResponse.Unmarshal(m, b)
}
func (m *LatestBlockHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestBlockHeightResponse.Marshal(b, m, deterministic)
}
func (m *LatestBlockHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestBlockHeightResponse.Merge(m, src)
}
func (m *LatestBlockHeightResponse) XXX_Size() int {
	return xxx_messageInfo_LatestBlockHeightResponse.Size(m)
}
func (m *LatestBlockHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestBlockHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestBlockHeightResponse proto.InternalMessageInfo

func (m *LatestBlockHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type DifficultHashRate struct {
	Difficulty           uint64   `protobuf:"varint,1,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DifficultHashRate) Reset()         { *m = DifficultHashRate{} }
func (m *DifficultHashRate) String() string { return proto.CompactTextString(m) }
func (*DifficultHashRate) ProtoMessage()    {}
func (*DifficultHashRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{7}
}

func (m *DifficultHashRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DifficultHashRate.Unmarshal(m, b)
}
func (m *DifficultHashRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DifficultHashRate.Marshal(b, m, deterministic)
}
func (m *DifficultHashRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DifficultHashRate.Merge(m, src)
}
func (m *DifficultHashRate) XXX_Size() int {
	return xxx_messageInfo_DifficultHashRate.Size(m)
}
func (m *DifficultHashRate) XXX_DiscardUnknown() {
	xxx_messageInfo_DifficultHashRate.DiscardUnknown(m)
}

var xxx_messageInfo_DifficultHashRate proto.InternalMessageInfo

func (m *DifficultHashRate) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type BlockDetail struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockDetail) Reset()         { *m = BlockDetail{} }
func (m *BlockDetail) String() string { return proto.CompactTextString(m) }
func (*BlockDetail) ProtoMessage()    {}
func (*BlockDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{8}
}

func (m *BlockDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockDetail.Unmarshal(m, b)
}
func (m *BlockDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockDetail.Marshal(b, m, deterministic)
}
func (m *BlockDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockDetail.Merge(m, src)
}
func (m *BlockDetail) XXX_Size() int {
	return xxx_messageInfo_BlockDetail.Size(m)
}
func (m *BlockDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockDetail.DiscardUnknown(m)
}

var xxx_messageInfo_BlockDetail proto.InternalMessageInfo

func (m *BlockDetail) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type GetBlockByBlockIdResponse struct {
	BlockDetail          *BlockDetail `protobuf:"bytes,1,opt,name=block_detail,json=blockDetail,proto3" json:"block_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBlockByBlockIdResponse) Reset()         { *m = GetBlockByBlockIdResponse{} }
func (m *GetBlockByBlockIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockByBlockIdResponse) ProtoMessage()    {}
func (*GetBlockByBlockIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{9}
}

func (m *GetBlockByBlockIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByBlockIdResponse.Unmarshal(m, b)
}
func (m *GetBlockByBlockIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByBlockIdResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockByBlockIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByBlockIdResponse.Merge(m, src)
}
func (m *GetBlockByBlockIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockByBlockIdResponse.Size(m)
}
func (m *GetBlockByBlockIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByBlockIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByBlockIdResponse proto.InternalMessageInfo

func (m *GetBlockByBlockIdResponse) GetBlockDetail() *BlockDetail {
	if m != nil {
		return m.BlockDetail
	}
	return nil
}

type TxnRequestItem struct {
	// Types that are valid to be assigned to TxnRequestedItems:
	//	*TxnRequestItem_LatestVersionRequestItem
	//	*TxnRequestItem_GetTransactionListRequestItem
	//	*TxnRequestItem_GetTransactionByVersionRequestItem
	TxnRequestedItems    isTxnRequestItem_TxnRequestedItems `protobuf_oneof:"txn_requested_items"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TxnRequestItem) Reset()         { *m = TxnRequestItem{} }
func (m *TxnRequestItem) String() string { return proto.CompactTextString(m) }
func (*TxnRequestItem) ProtoMessage()    {}
func (*TxnRequestItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{10}
}

func (m *TxnRequestItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnRequestItem.Unmarshal(m, b)
}
func (m *TxnRequestItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnRequestItem.Marshal(b, m, deterministic)
}
func (m *TxnRequestItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnRequestItem.Merge(m, src)
}
func (m *TxnRequestItem) XXX_Size() int {
	return xxx_messageInfo_TxnRequestItem.Size(m)
}
func (m *TxnRequestItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnRequestItem.DiscardUnknown(m)
}

var xxx_messageInfo_TxnRequestItem proto.InternalMessageInfo

type isTxnRequestItem_TxnRequestedItems interface {
	isTxnRequestItem_TxnRequestedItems()
}

type TxnRequestItem_LatestVersionRequestItem struct {
	LatestVersionRequestItem *empty.Empty `protobuf:"bytes,1,opt,name=latest_version_request_item,json=latestVersionRequestItem,proto3,oneof"`
}

type TxnRequestItem_GetTransactionListRequestItem struct {
	GetTransactionListRequestItem *GetTransactionListRequest `protobuf:"bytes,2,opt,name=get_transaction_list_request_item,json=getTransactionListRequestItem,proto3,oneof"`
}

type TxnRequestItem_GetTransactionByVersionRequestItem struct {
	GetTransactionByVersionRequestItem *Version `protobuf:"bytes,3,opt,name=get_transaction_by_version_request_item,json=getTransactionByVersionRequestItem,proto3,oneof"`
}

func (*TxnRequestItem_LatestVersionRequestItem) isTxnRequestItem_TxnRequestedItems() {}

func (*TxnRequestItem_GetTransactionListRequestItem) isTxnRequestItem_TxnRequestedItems() {}

func (*TxnRequestItem_GetTransactionByVersionRequestItem) isTxnRequestItem_TxnRequestedItems() {}

func (m *TxnRequestItem) GetTxnRequestedItems() isTxnRequestItem_TxnRequestedItems {
	if m != nil {
		return m.TxnRequestedItems
	}
	return nil
}

func (m *TxnRequestItem) GetLatestVersionRequestItem() *empty.Empty {
	if x, ok := m.GetTxnRequestedItems().(*TxnRequestItem_LatestVersionRequestItem); ok {
		return x.LatestVersionRequestItem
	}
	return nil
}

func (m *TxnRequestItem) GetGetTransactionListRequestItem() *GetTransactionListRequest {
	if x, ok := m.GetTxnRequestedItems().(*TxnRequestItem_GetTransactionListRequestItem); ok {
		return x.GetTransactionListRequestItem
	}
	return nil
}

func (m *TxnRequestItem) GetGetTransactionByVersionRequestItem() *Version {
	if x, ok := m.GetTxnRequestedItems().(*TxnRequestItem_GetTransactionByVersionRequestItem); ok {
		return x.GetTransactionByVersionRequestItem
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TxnRequestItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TxnRequestItem_LatestVersionRequestItem)(nil),
		(*TxnRequestItem_GetTransactionListRequestItem)(nil),
		(*TxnRequestItem_GetTransactionByVersionRequestItem)(nil),
	}
}

type TxnResponseItem struct {
	// Types that are valid to be assigned to TxnResponseItems:
	//	*TxnResponseItem_LatestVersionResponseItem
	//	*TxnResponseItem_GetTransactionListResponseItem
	//	*TxnResponseItem_GetTransactionByVersionResponseItem
	TxnResponseItems     isTxnResponseItem_TxnResponseItems `protobuf_oneof:"txn_response_items"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TxnResponseItem) Reset()         { *m = TxnResponseItem{} }
func (m *TxnResponseItem) String() string { return proto.CompactTextString(m) }
func (*TxnResponseItem) ProtoMessage()    {}
func (*TxnResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{11}
}

func (m *TxnResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnResponseItem.Unmarshal(m, b)
}
func (m *TxnResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnResponseItem.Marshal(b, m, deterministic)
}
func (m *TxnResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnResponseItem.Merge(m, src)
}
func (m *TxnResponseItem) XXX_Size() int {
	return xxx_messageInfo_TxnResponseItem.Size(m)
}
func (m *TxnResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_TxnResponseItem proto.InternalMessageInfo

type isTxnResponseItem_TxnResponseItems interface {
	isTxnResponseItem_TxnResponseItems()
}

type TxnResponseItem_LatestVersionResponseItem struct {
	LatestVersionResponseItem *LatestVersionResponse `protobuf:"bytes,1,opt,name=latest_version_response_item,json=latestVersionResponseItem,proto3,oneof"`
}

type TxnResponseItem_GetTransactionListResponseItem struct {
	GetTransactionListResponseItem *GetTransactionListResponse `protobuf:"bytes,2,opt,name=get_transaction_list_response_item,json=getTransactionListResponseItem,proto3,oneof"`
}

type TxnResponseItem_GetTransactionByVersionResponseItem struct {
	GetTransactionByVersionResponseItem *GetTransactionByVersionResponse `protobuf:"bytes,3,opt,name=get_transaction_by_version_response_item,json=getTransactionByVersionResponseItem,proto3,oneof"`
}

func (*TxnResponseItem_LatestVersionResponseItem) isTxnResponseItem_TxnResponseItems() {}

func (*TxnResponseItem_GetTransactionListResponseItem) isTxnResponseItem_TxnResponseItems() {}

func (*TxnResponseItem_GetTransactionByVersionResponseItem) isTxnResponseItem_TxnResponseItems() {}

func (m *TxnResponseItem) GetTxnResponseItems() isTxnResponseItem_TxnResponseItems {
	if m != nil {
		return m.TxnResponseItems
	}
	return nil
}

func (m *TxnResponseItem) GetLatestVersionResponseItem() *LatestVersionResponse {
	if x, ok := m.GetTxnResponseItems().(*TxnResponseItem_LatestVersionResponseItem); ok {
		return x.LatestVersionResponseItem
	}
	return nil
}

func (m *TxnResponseItem) GetGetTransactionListResponseItem() *GetTransactionListResponse {
	if x, ok := m.GetTxnResponseItems().(*TxnResponseItem_GetTransactionListResponseItem); ok {
		return x.GetTransactionListResponseItem
	}
	return nil
}

func (m *TxnResponseItem) GetGetTransactionByVersionResponseItem() *GetTransactionByVersionResponse {
	if x, ok := m.GetTxnResponseItems().(*TxnResponseItem_GetTransactionByVersionResponseItem); ok {
		return x.GetTransactionByVersionResponseItem
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TxnResponseItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TxnResponseItem_LatestVersionResponseItem)(nil),
		(*TxnResponseItem_GetTransactionListResponseItem)(nil),
		(*TxnResponseItem_GetTransactionByVersionResponseItem)(nil),
	}
}

type Version struct {
	Ver                  uint64   `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{12}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVer() uint64 {
	if m != nil {
		return m.Ver
	}
	return 0
}

type LatestVersionResponse struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestVersionResponse) Reset()         { *m = LatestVersionResponse{} }
func (m *LatestVersionResponse) String() string { return proto.CompactTextString(m) }
func (*LatestVersionResponse) ProtoMessage()    {}
func (*LatestVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{13}
}

func (m *LatestVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestVersionResponse.Unmarshal(m, b)
}
func (m *LatestVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestVersionResponse.Marshal(b, m, deterministic)
}
func (m *LatestVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestVersionResponse.Merge(m, src)
}
func (m *LatestVersionResponse) XXX_Size() int {
	return xxx_messageInfo_LatestVersionResponse.Size(m)
}
func (m *LatestVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestVersionResponse proto.InternalMessageInfo

func (m *LatestVersionResponse) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type GetTransactionListRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionListRequest) Reset()         { *m = GetTransactionListRequest{} }
func (m *GetTransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListRequest) ProtoMessage()    {}
func (*GetTransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{14}
}

func (m *GetTransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListRequest.Unmarshal(m, b)
}
func (m *GetTransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListRequest.Merge(m, src)
}
func (m *GetTransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListRequest.Size(m)
}
func (m *GetTransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListRequest proto.InternalMessageInfo

func (m *GetTransactionListRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type GetTransactionListResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionListResponse) Reset()         { *m = GetTransactionListResponse{} }
func (m *GetTransactionListResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListResponse) ProtoMessage()    {}
func (*GetTransactionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{15}
}

func (m *GetTransactionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListResponse.Unmarshal(m, b)
}
func (m *GetTransactionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListResponse.Merge(m, src)
}
func (m *GetTransactionListResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListResponse.Size(m)
}
func (m *GetTransactionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListResponse proto.InternalMessageInfo

func (m *GetTransactionListResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetTransactionByVersionResponse struct {
	Txn                  *Transaction `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTransactionByVersionResponse) Reset()         { *m = GetTransactionByVersionResponse{} }
func (m *GetTransactionByVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionByVersionResponse) ProtoMessage()    {}
func (*GetTransactionByVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92013ac430d0de85, []int{16}
}

func (m *GetTransactionByVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionByVersionResponse.Unmarshal(m, b)
}
func (m *GetTransactionByVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionByVersionResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionByVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionByVersionResponse.Merge(m, src)
}
func (m *GetTransactionByVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionByVersionResponse.Size(m)
}
func (m *GetTransactionByVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionByVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionByVersionResponse proto.InternalMessageInfo

func (m *GetTransactionByVersionResponse) GetTxn() *Transaction {
	if m != nil {
		return m.Txn
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockRequestItem)(nil), "types.BlockRequestItem")
	proto.RegisterType((*BlockResponseItem)(nil), "types.BlockResponseItem")
	proto.RegisterType((*BlockSummary)(nil), "types.BlockSummary")
	proto.RegisterType((*GetBlockSummaryListRequest)(nil), "types.GetBlockSummaryListRequest")
	proto.RegisterType((*BlockId)(nil), "types.BlockId")
	proto.RegisterType((*GetBlockSummaryListResponse)(nil), "types.GetBlockSummaryListResponse")
	proto.RegisterType((*LatestBlockHeightResponse)(nil), "types.LatestBlockHeightResponse")
	proto.RegisterType((*DifficultHashRate)(nil), "types.DifficultHashRate")
	proto.RegisterType((*BlockDetail)(nil), "types.BlockDetail")
	proto.RegisterType((*GetBlockByBlockIdResponse)(nil), "types.GetBlockByBlockIdResponse")
	proto.RegisterType((*TxnRequestItem)(nil), "types.TxnRequestItem")
	proto.RegisterType((*TxnResponseItem)(nil), "types.TxnResponseItem")
	proto.RegisterType((*Version)(nil), "types.Version")
	proto.RegisterType((*LatestVersionResponse)(nil), "types.LatestVersionResponse")
	proto.RegisterType((*GetTransactionListRequest)(nil), "types.GetTransactionListRequest")
	proto.RegisterType((*GetTransactionListResponse)(nil), "types.GetTransactionListResponse")
	proto.RegisterType((*GetTransactionByVersionResponse)(nil), "types.GetTransactionByVersionResponse")
}

func init() { proto.RegisterFile("explorer.proto", fileDescriptor_92013ac430d0de85) }

var fileDescriptor_92013ac430d0de85 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x6e, 0xe3, 0x36,
	0x14, 0xb5, 0xad, 0x24, 0xce, 0xdc, 0x38, 0x99, 0x09, 0xf3, 0xa8, 0x1d, 0xa7, 0x19, 0x9b, 0x19,
	0x4c, 0x5d, 0x14, 0xf0, 0x00, 0x49, 0xdb, 0x7d, 0x8d, 0x19, 0xc4, 0x29, 0x66, 0xa5, 0x06, 0xed,
	0x52, 0x95, 0x6d, 0x46, 0x16, 0x2a, 0x8b, 0xae, 0x48, 0x07, 0xd6, 0xaa, 0xff, 0xd0, 0x4d, 0xbf,
	0xac, 0x7f, 0xd0, 0xaf, 0xe8, 0xaa, 0xd0, 0x25, 0xad, 0x50, 0x2f, 0x07, 0xdd, 0x89, 0xbc, 0x8f,
	0xc3, 0x7b, 0x0e, 0x79, 0x04, 0x47, 0x6c, 0xbd, 0x0c, 0x78, 0xc4, 0xa2, 0xe1, 0x32, 0xe2, 0x92,
	0x93, 0x5d, 0x19, 0x2f, 0x99, 0xb8, 0x38, 0x96, 0x91, 0x1b, 0x0a, 0x77, 0x2a, 0x7d, 0x1e, 0xaa,
	0xc8, 0x45, 0xd7, 0xe3, 0xdc, 0x0b, 0xd8, 0x07, 0x5c, 0x4d, 0x56, 0x8f, 0x1f, 0xd8, 0x62, 0x29,
	0x63, 0x15, 0xa4, 0x7f, 0x59, 0xf0, 0x66, 0x14, 0xf0, 0xe9, 0x6f, 0x36, 0xfb, 0x7d, 0xc5, 0x84,
	0xbc, 0x97, 0x6c, 0x41, 0xbe, 0x85, 0xc3, 0x49, 0xb2, 0xe7, 0xf8, 0x33, 0xc7, 0x97, 0x6c, 0xd1,
	0xae, 0xf7, 0xea, 0x83, 0x83, 0x9b, 0xa3, 0x21, 0x62, 0x0c, 0x31, 0xff, 0x7e, 0x36, 0xae, 0xd9,
	0x07, 0x13, 0xf5, 0x89, 0x55, 0x4b, 0xb8, 0xf6, 0x98, 0x74, 0x54, 0xa5, 0x58, 0x2d, 0x16, 0x6e,
	0x14, 0x3b, 0x81, 0x2f, 0xa4, 0x13, 0xa9, 0xde, 0xaa, 0x57, 0x03, 0x7b, 0xf5, 0x75, 0xaf, 0x3b,
	0x26, 0xb1, 0xdd, 0x4f, 0x2a, 0xff, 0xb3, 0x2f, 0xa4, 0x3e, 0xc9, 0xb8, 0x66, 0x5f, 0x79, 0x95,
	0x51, 0x44, 0xfc, 0x15, 0x7a, 0x81, 0x2b, 0x93, 0xce, 0x0a, 0x74, 0xce, 0x7c, 0x6f, 0x9e, 0x83,
	0xb3, 0x10, 0xee, 0x7c, 0xa8, 0x48, 0x18, 0x6e, 0x48, 0x18, 0x7e, 0x4a, 0x48, 0x18, 0xd7, 0xec,
	0x4b, 0xd5, 0x01, 0x61, 0xc6, 0x58, 0x9f, 0x43, 0x98, 0xf9, 0x8f, 0x8f, 0xfe, 0x74, 0x15, 0x48,
	0x67, 0xee, 0x8a, 0xb9, 0x13, 0xb9, 0x92, 0x65, 0x11, 0x76, 0x5e, 0x42, 0x48, 0x3b, 0x8c, 0x5d,
	0x31, 0xb7, 0x5d, 0xc9, 0x0c, 0x84, 0xd1, 0x17, 0x70, 0xa6, 0x0e, 0xaf, 0x7b, 0x32, 0x45, 0xb9,
	0xa0, 0xff, 0x58, 0x70, 0xac, 0x95, 0x11, 0x4b, 0x1e, 0x0a, 0x86, 0x07, 0x0a, 0x4d, 0x92, 0x27,
	0xb1, 0x93, 0xea, 0x14, 0xe9, 0x2c, 0x53, 0xb0, 0x5e, 0x8e, 0xe4, 0x51, 0xac, 0xa5, 0xdb, 0xb4,
	0x1c, 0xd7, 0xec, 0x2f, 0xbd, 0xaa, 0x20, 0xe2, 0x09, 0x78, 0x57, 0x29, 0xaa, 0x09, 0xa8, 0x54,
	0xa5, 0xdb, 0x54, 0x4d, 0x21, 0xdf, 0x7a, 0xd5, 0x61, 0x04, 0x0d, 0xa0, 0x5f, 0xae, 0xab, 0x89,
	0x68, 0x65, 0x46, 0xfc, 0x5c, 0x54, 0xf1, 0x79, 0xc4, 0xa0, 0x2a, 0x88, 0x68, 0x33, 0xe8, 0x97,
	0x6b, 0x6c, 0xa2, 0x29, 0x91, 0xdb, 0x1a, 0xed, 0x63, 0x5e, 0xd1, 0x04, 0xa5, 0x44, 0xe6, 0x67,
	0x94, 0xd1, 0x39, 0x9c, 0x6e, 0x74, 0x36, 0xfa, 0x0a, 0xfa, 0x67, 0x03, 0x5a, 0x26, 0x19, 0xa4,
	0x03, 0xfb, 0x1b, 0x51, 0x51, 0xc6, 0x96, 0xdd, 0xd4, 0xaf, 0x8c, 0x9c, 0xc3, 0x9e, 0xa2, 0x02,
	0xe9, 0xde, 0xb1, 0xf5, 0x8a, 0x74, 0xe1, 0xd5, 0xd2, 0x8d, 0x58, 0x28, 0x93, 0x1a, 0x0b, 0x6b,
	0xf6, 0xd5, 0xc6, 0xfd, 0x8c, 0xdc, 0xc0, 0x99, 0x3b, 0x9d, 0xae, 0x16, 0xab, 0xc0, 0x95, 0x3c,
	0x72, 0x22, 0xce, 0xd5, 0x94, 0x38, 0x52, 0xcb, 0x3e, 0x31, 0x82, 0x36, 0xe7, 0x78, 0x78, 0xf2,
	0x1e, 0x5e, 0x0b, 0x89, 0x24, 0xa4, 0xd9, 0xbb, 0x98, 0x7d, 0x88, 0xdb, 0x69, 0xde, 0x29, 0xec,
	0x2e, 0xfc, 0x90, 0x45, 0xed, 0x3d, 0x8c, 0xaa, 0x45, 0xb2, 0x1b, 0xf2, 0x70, 0xca, 0xda, 0x4d,
	0x3c, 0xa5, 0x5a, 0x24, 0x87, 0x97, 0x6e, 0xe4, 0x31, 0xd9, 0xde, 0xc7, 0x64, 0xbd, 0x22, 0x04,
	0x76, 0xdc, 0xc0, 0xe3, 0xed, 0x57, 0xbd, 0xfa, 0xe0, 0xd0, 0xc6, 0x6f, 0x7a, 0x07, 0x17, 0xd5,
	0xc6, 0x40, 0xbe, 0xce, 0x31, 0x54, 0x70, 0xa6, 0x94, 0x31, 0xda, 0x81, 0xa6, 0xde, 0x23, 0x47,
	0xd0, 0x48, 0x19, 0x6d, 0xf8, 0x33, 0xfa, 0x23, 0x74, 0xb7, 0x5c, 0x53, 0xf2, 0x0d, 0xec, 0x61,
	0x13, 0xd1, 0xae, 0xf7, 0xac, 0xc1, 0xc1, 0xcd, 0x89, 0x09, 0xa1, 0x0b, 0x6c, 0x9d, 0x42, 0x6f,
	0xa1, 0x53, 0x79, 0x01, 0x0d, 0xd5, 0xea, 0xa6, 0x6a, 0xf4, 0x16, 0x8e, 0x0b, 0xf7, 0x88, 0x5c,
	0x01, 0xa4, 0xf7, 0x28, 0xd6, 0x05, 0xc6, 0x0e, 0xbd, 0x86, 0x03, 0xc4, 0xf8, 0xc8, 0xa4, 0xeb,
	0x07, 0x09, 0xd5, 0x93, 0x58, 0x32, 0xa1, 0xe7, 0x52, 0x0b, 0x6a, 0x43, 0xa7, 0xf2, 0xc9, 0x93,
	0xef, 0xa0, 0xa5, 0xd8, 0x9b, 0x61, 0x0b, 0xcd, 0x20, 0x31, 0xc7, 0x53, 0xcd, 0xb5, 0xbb, 0xab,
	0x05, 0xfd, 0xbb, 0x01, 0x47, 0x0f, 0xeb, 0xd0, 0x34, 0xc7, 0x5f, 0xa0, 0xab, 0x9f, 0xe9, 0x13,
	0x8b, 0x84, 0xcf, 0xc3, 0xac, 0x2f, 0xd6, 0x5f, 0xf0, 0xc5, 0xb6, 0x2a, 0xfe, 0x59, 0xd5, 0x9a,
	0x8d, 0x03, 0xe8, 0x27, 0xa6, 0x63, 0xfc, 0xca, 0x2a, 0xff, 0x23, 0x86, 0xc5, 0x3d, 0x3c, 0xa7,
	0x67, 0x7f, 0x23, 0x89, 0xc5, 0x95, 0x07, 0x11, 0x8d, 0xc1, 0x57, 0x79, 0xb4, 0x49, 0x5c, 0x3e,
	0x92, 0x95, 0xb9, 0x6d, 0xfa, 0xe4, 0xe3, 0x9a, 0x4d, 0xb3, 0x08, 0xa3, 0xb8, 0x38, 0xd4, 0xe8,
	0x0c, 0x4e, 0xe4, 0x3a, 0x2c, 0xd8, 0xfc, 0xbf, 0x0d, 0x78, 0x8d, 0xbc, 0x1a, 0x8e, 0xe4, 0xc0,
	0x65, 0x81, 0xd8, 0xa2, 0xbb, 0x5f, 0x66, 0xac, 0x2f, 0x45, 0x4c, 0x6d, 0xaf, 0x13, 0x94, 0x05,
	0x10, 0x80, 0x03, 0xad, 0x20, 0xb8, 0xe8, 0xe9, 0xfd, 0x2d, 0x0c, 0xa7, 0x58, 0x57, 0x5e, 0x65,
	0x14, 0x01, 0xff, 0x80, 0xc1, 0x56, 0x8e, 0x8b, 0xc6, 0xfe, 0xbe, 0x14, 0xd6, 0x60, 0x36, 0xc5,
	0xbe, 0xf6, 0xb6, 0xa7, 0x20, 0xfb, 0xa7, 0x40, 0x14, 0xfb, 0x19, 0xf3, 0xed, 0x42, 0x53, 0x27,
	0x93, 0x37, 0x60, 0x3d, 0xb1, 0x48, 0xbf, 0xb8, 0xe4, 0x93, 0xfe, 0x00, 0x67, 0xa5, 0xd4, 0x92,
	0x01, 0x34, 0xf5, 0xc9, 0x73, 0xf6, 0xb3, 0x49, 0xdc, 0x84, 0xe9, 0x27, 0x7c, 0x88, 0xe5, 0x77,
	0xef, 0x7f, 0xb4, 0x79, 0x40, 0x3b, 0xac, 0xe0, 0x97, 0x7c, 0x0f, 0x2d, 0x83, 0xd7, 0x8d, 0x5f,
	0x6d, 0x1e, 0xb4, 0x51, 0x65, 0x67, 0xf2, 0xe8, 0x1d, 0xbc, 0x7d, 0x81, 0x5c, 0xf2, 0x0e, 0x2c,
	0xb9, 0x0e, 0x73, 0x16, 0x61, 0x76, 0x4c, 0xc2, 0x93, 0x3d, 0x7c, 0xda, 0xb7, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x71, 0xf2, 0x6e, 0x93, 0x0a, 0x00, 0x00,
}
