// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator_change.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This is used to prove validator changes.  When a validator is changing, it
// triggers an event on /validator_change_account/events/sent.  To tell the
// client about validator changes, we query
// /validator_change_account/events/sent to get all versions that contain
// validator changes after the version that we are trying to update from. For
// each of these versions, the old validator set would have signed the ledger
// info at that version.  The client needs this as well as the event results +
// proof.  The client can then verify that these events were under the current
// tree and that the changes were signed by the old validators (and that the
// events correctly show which validators are the new validators).
type ValidatorChangeEventWithProof struct {
	LedgerInfoWithSigs   []*LedgerInfoWithSignatures `protobuf:"bytes,1,rep,name=ledger_info_with_sigs,json=ledgerInfoWithSigs,proto3" json:"ledger_info_with_sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ValidatorChangeEventWithProof) Reset()         { *m = ValidatorChangeEventWithProof{} }
func (m *ValidatorChangeEventWithProof) String() string { return proto.CompactTextString(m) }
func (*ValidatorChangeEventWithProof) ProtoMessage()    {}
func (*ValidatorChangeEventWithProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_484a7446a4b3dd15, []int{0}
}

func (m *ValidatorChangeEventWithProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorChangeEventWithProof.Unmarshal(m, b)
}
func (m *ValidatorChangeEventWithProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorChangeEventWithProof.Marshal(b, m, deterministic)
}
func (m *ValidatorChangeEventWithProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorChangeEventWithProof.Merge(m, src)
}
func (m *ValidatorChangeEventWithProof) XXX_Size() int {
	return xxx_messageInfo_ValidatorChangeEventWithProof.Size(m)
}
func (m *ValidatorChangeEventWithProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorChangeEventWithProof.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorChangeEventWithProof proto.InternalMessageInfo

func (m *ValidatorChangeEventWithProof) GetLedgerInfoWithSigs() []*LedgerInfoWithSignatures {
	if m != nil {
		return m.LedgerInfoWithSigs
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorChangeEventWithProof)(nil), "types.ValidatorChangeEventWithProof")
}

func init() { proto.RegisterFile("validator_change.proto", fileDescriptor_484a7446a4b3dd15) }

var fileDescriptor_484a7446a4b3dd15 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0x8a, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0xe2, 0x49, 0x2d, 0x4b, 0xcd, 0x2b,
	0x29, 0x86, 0x08, 0x4a, 0x09, 0xe6, 0xa4, 0xa6, 0xa4, 0xa7, 0x16, 0xc5, 0x67, 0xe6, 0xa5, 0xe5,
	0x43, 0x84, 0x94, 0x8a, 0xb9, 0x64, 0xc3, 0x60, 0x26, 0x38, 0x83, 0x0d, 0x70, 0x05, 0xe9, 0x08,
	0xcf, 0x2c, 0xc9, 0x08, 0x28, 0xca, 0xcf, 0x4f, 0x13, 0x0a, 0xe2, 0x12, 0x45, 0xd2, 0x15, 0x5f,
	0x9e, 0x59, 0x92, 0x11, 0x5f, 0x9c, 0x99, 0x5e, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24,
	0xaf, 0x07, 0xb6, 0x48, 0xcf, 0x07, 0xac, 0xc6, 0x33, 0x2f, 0x2d, 0x1f, 0xa4, 0x35, 0x38, 0x33,
	0x3d, 0x2f, 0xb1, 0xa4, 0xb4, 0x28, 0xb5, 0x38, 0x48, 0x28, 0x07, 0x5d, 0xa6, 0x38, 0x89, 0x0d,
	0x6c, 0xb7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf6, 0x9a, 0x7a, 0xbd, 0x00, 0x00, 0x00,
}
