[network]
address = 'localhost'
port = 9000

[node_net_work]
addr = 'localhost'
max_sockets = 20
in_memory = false
seeds = []

[wallet]
chain_address = 'localhost'
chain_port = 8000
store_dir="wallet"