[rpc_config]
address = 'localhost'
port = 9000

[rest_config]
address = '127.0.0.1'
port = 7000

[net_config]
listen = '/ip4/127.0.0.1/tcp/10000'
max_sockets = 20
in_memory = false
seeds = []

[wallet]
chain_address = 'localhost'
chain_port = 8000
store_dir='alice'