[rpc_config]
address = 'localhost'
port = 9000
timeout = 200000
auto_approve = true

[rest_config]
address = '127.0.0.1'
port = 7000

[net_config]
listen = '/ip4/127.0.0.1/tcp/10000'
max_sockets = 20
in_memory = false
seeds = []

[wallet]
chain_address = '39.98.196.244'
chain_port = 8001
store_dir = 'alice'
