version: '3'
services:
  wallet_node:
    image: docker.pkg.github.com/starcoinorg/stargate/node:latest
    ports:
    - "9000:9000"
    volumes:
      - ./logs/nodelogs:/logs
      - ./wallet:/opt/starcoin/etc
  gateway:
    image: docker.pkg.github.com/starcoinorg/stargate/gateway:latest
    environment:
        GATEWAY_PORT: ":8080"
        NODE_PORT: ":9000"
    volumes:
        - ./logs/gatewaylogs:/gateway/log
    ports:
    - "8080:8080"
    depends_on:
      - wallet_node
