[package]
name = "faucet-client"
version = "0.1.0"
authors = ["tiangong3624749 <tiangong3624749@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "=0.3.0-alpha.19", package = "futures-preview", features = ["compat"] }
futures_01 = { version = "0.1.28", package = "futures" }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
rand = "0.6.5"
libra-crypto = { path = "../../libra/crypto/crypto", version = "0.1.0" }
faucet-proto = { path = "../faucet-proto", version = "0.1.0" }
libra-types = { path = "../../libra/types", version = "0.1.0" }
anyhow = "1.0"

[dev-dependencies]
faucet-service = { path = "../faucet-service" }
sgchain = { path = "../../sgchain" }
libra-logger = { path = "../../libra/common/logger"}