name: PR
on: pull_request
jobs:
  fmt_build_test:
    name: fmt_build_test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          components: rustfmt,clippy

      - name: run fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: install protobuf
        env:
          PROTOC_VERSION: 3.8.0
          PROTOC_ZIP: protoc-3.8.0-linux-x86_64.zip
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP && sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc && sudo unzip -o $PROTOC_ZIP -d /usr/local include/* && rm -f $PROTOC_ZIP && echo "protoc is installed to /usr/local/bin/"

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: test
        env:
          RUST_LOG: info
          RUST_BACKTRACE: full
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --exclude network-libp2p --exclude sgnetwork -- --test-threads=1 --nocapture
