[package]
name = "faucet-service"
version = "0.1.0"
authors = ["tiangong3624749 <tiangong3624749@163.com>"]
edition = "2018"

[dependencies]
toml = { version = "0.5.3", default-features = false }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
sgchain = { path = "../../sgchain" }
libra-types = { path = "../../libra/types" }
generate-keypair = { path = "../../libra/config/generate-keypair", version = "0.1.0" }
libra-config = { path = "../../libra/config", version = "0.1.0" }
tokio = { version = "0.2", features = ["full"] }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
proptest = { version = "0.9.2", optional = true }
proptest-derive = { version = "0.1.0", optional = true }
prost = "0.6.1"
faucet-proto = { path = "../faucet-proto", version = "0.1.0" }
grpc-helpers = { path = "../../libra/common/grpc-helpers", version = "0.1.0" }
anyhow = "1.0"
libra-crypto = { path = "../../libra/crypto/crypto" }
libra-logger = { path = "../../libra/common/logger"}
base64 = "0.11.0"
